name: Talisman Secrets Scan

on: [push, pull_request]

jobs:
 talisman-scan:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Install Talisman
        run: |
          curl -fsSL https://raw.githubusercontent.com/thoughtworks/talisman/main/install.sh | bash
          sudo mv talisman /usr/local/bin/

      - name: Detect secrets with Talisman
        run: |
          talisman --scan
