name: Talisman Secrets Scan

on: [push, pull_request]

jobs:
 talisman-scan:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Install Talisman
        run: |
          curl -L -o talisman.tar.gz https://github.com/thoughtworks/talisman/releases/latest/download/talisman_linux_amd64.tar.gz
          tar xzf talisman.tar.gz
          sudo mv talisman /usr/local/bin/

      - name: Detect secrets with Talisman
        run: |
          talisman --scan
